# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(967, 600)
        Widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.ironManBack = QtWidgets.QLabel(Widget)
        self.ironManBack.setGeometry(QtCore.QRect(600, 60, 371, 531))
        self.ironManBack.setText("")
        self.ironManBack.setPixmap(QtGui.QPixmap("C:/Users/subha/Desktop/Final/iron-man-super-hero-sp-pos-122-large-original-imaegyghjfregdad.webp"))
        self.ironManBack.setScaledContents(True)
        self.ironManBack.setObjectName("label")
        self.kartisTechLabel = QtWidgets.QLabel(Widget)
        self.kartisTechLabel.setGeometry(QtCore.QRect(320, 0, 351, 71))
        self.kartisTechLabel.setText("")
        self.kartisTechLabel.setPixmap(QtGui.QPixmap("C:\\Users\\subha\\Desktop\\Final/0000 (1).png"))
        self.kartisTechLabel.setScaledContents(True)
        self.kartisTechLabel.setObjectName("kartisTechLabel")
        self.videoBack = QtWidgets.QLabel(Widget)
        self.videoBack.setGeometry(QtCore.QRect(10, 70, 571, 441))
        self.videoBack.setStyleSheet("border-color: rgb(255, 255, 255);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "border-style: solid;\n"
                                   "border-width: 1px 1px 1px 1px;")
        self.videoBack.setText("")
        self.videoBack.setObjectName("videoBack")
        self.loginButton = QtWidgets.QPushButton(Widget)
        self.loginButton.setGeometry(QtCore.QRect(40, 520, 161, 61))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("border-image: url(C:/Users/subha/Desktop/Final/0000 (3).png);")
        self.loginButton.setText("")
        self.loginButton.setObjectName("loginButton")
        self.exitButton = QtWidgets.QPushButton(Widget)
        self.exitButton.setGeometry(QtCore.QRect(310, 520, 161, 61))
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setStyleSheet("border-image: url(C:/Users/subha/Desktop/Final/0000 (2).png);")
        self.exitButton.setText("")
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
