# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1280, 720)
        Widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.coding_label = QtWidgets.QLabel(Widget)
        self.coding_label.setGeometry(QtCore.QRect(10, 10, 231, 161))
        self.coding_label.setText("")
        self.coding_label.setPixmap(QtGui.QPixmap("C:\\Users\\subha\\Desktop\\Final/NZzo.gif"))
        self.coding_label.setScaledContents(True)
        self.coding_label.setObjectName("coding_label")
        self.Jervis_bel_2 = QtWidgets.QLabel(Widget)
        self.Jervis_bel_2.setGeometry(QtCore.QRect(360, 0, 451, 101))
        self.Jervis_bel_2.setText("")
        self.Jervis_bel_2.setPixmap(QtGui.QPixmap("C:\\Users\\subha\\Desktop\\Final/0000 (1).png"))
        self.Jervis_bel_2.setScaledContents(True)
        self.Jervis_bel_2.setObjectName("Jervis_bel_2")
        self.iron_label = QtWidgets.QLabel(Widget)
        self.iron_label.setGeometry(QtCore.QRect(870, 0, 401, 621))
        self.iron_label.setText("")
        self.iron_label.setPixmap(QtGui.QPixmap("C:\\Users\\subha\\Desktop\\Final/iron-man-super-hero-sp-pos-122-large-original-imaegyghjfregdad.webp"))
        self.iron_label.setScaledContents(True)
        self.iron_label.setObjectName("iron_label")
        self.label_4 = QtWidgets.QLabel(Widget)
        self.label_4.setGeometry(QtCore.QRect(400, 120, 421, 241))
        self.label_4.setStyleSheet("background-color: transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\subha\\Desktop\\Final/da2h0ba-4f905a80-3438-48c6-957f-3ef873f7e7f4.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.Terminal = QtWidgets.QPlainTextEdit(Widget)
        self.Terminal.setGeometry(QtCore.QRect(0, 450, 1321, 181))
        self.Terminal.setStyleSheet("background-color: transparent;")
        self.Terminal.setObjectName("Terminal")
        self.commond = QtWidgets.QLineEdit(Widget)
        self.commond.setGeometry(QtCore.QRect(0, 637, 1131, 41))
        self.commond.setStyleSheet("background-color: transparent;")
        self.commond.setObjectName("commond")
        self.Enter_Button = QtWidgets.QPushButton(Widget)
        self.Enter_Button.setGeometry(QtCore.QRect(1020, 640, 83, 29))
        self.Enter_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Enter_Button.setStyleSheet("border-image: url(C:/Users/subha/Desktop/Final/0000 (6).png);\n"
                                        "background-color: transparent;\n"
                                        "border-color: rgb(255, 255, 255);\n"
                                        "border-style: solid;\n"
                                        "border-left: 5px;\n"
                                        "border-radius: none;")
        self.Enter_Button.setText("")
        self.Enter_Button.setObjectName("Enter_Button")
        self.Exit_Button = QtWidgets.QPushButton(Widget)
        self.Exit_Button.setGeometry(QtCore.QRect(1150, 630, 111, 61))
        self.Exit_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Exit_Button.setStyleSheet("border-image: url(C:/Users/subha/Desktop/Final/0000 (2).png);\n"
                                       "background-color: transparent;\n"
                                       "border-radius: 30px;\n"
                                       "border-width: 5px 5px 5px 5px;\n"
                                       "border-color: rgb(255, 255, 255);\n"
                                       "border-style: solid;")
        self.Exit_Button.setText("")
        self.Exit_Button.setObjectName("Exit_Button")
        self.loading = QtWidgets.QLabel(Widget)
        self.loading.setGeometry(QtCore.QRect(20, 120, 391, 241))
        self.loading.setStyleSheet("background-color: transparent;")
        self.loading.setText("")
        self.loading.setPixmap(QtGui.QPixmap("C:\\Users\\subha\\Desktop\\Final/00545cb7179c504433d4c8f5e845f286.gif"))
        self.loading.setScaledContents(True)
        self.loading.setObjectName("loading")
        self.speaking = QtWidgets.QLabel(Widget)
        self.speaking.setGeometry(QtCore.QRect(30, 110, 391, 271))
        self.speaking.setStyleSheet("background-color: transparent;")
        self.speaking.setText("")
        self.speaking.setPixmap(QtGui.QPixmap("C:\\Users\\subha\\Desktop\\Final/ava_ai.gif"))
        self.speaking.setScaledContents(True)
        self.speaking.setObjectName("speaking")
        self.listining = QtWidgets.QLabel(Widget)
        self.listining.setGeometry(QtCore.QRect(20, 100, 391, 321))
        self.listining.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.listining.setText("")
        self.listining.setPixmap(QtGui.QPixmap("C:\\Users\\subha\\Desktop\\Final/64bab4e3c67b53f2f0cb5ae1_Slang Labs Logo Animations.gif"))
        self.listining.setScaledContents(True)
        self.listining.setObjectName("listining")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.Terminal.setPlaceholderText(_translate("Widget", "Terminal Output goes here"))
        self.commond.setPlaceholderText(_translate("Widget", "Enter Your Commond"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
