# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindowClass(object):
    def setupUi(self, loginWindowClass):
        loginWindowClass.setObjectName("loginWindowClass")
        loginWindowClass.resize(1000, 720)
        loginWindowClass.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.JervisLabel = QtWidgets.QLabel(loginWindowClass)
        self.JervisLabel.setGeometry(QtCore.QRect(270, 0, 441, 71))
        self.JervisLabel.setText("")
        self.JervisLabel.setPixmap(QtGui.QPixmap("C:\\Users\\subha\\Desktop\\Final/0000 (1).png"))
        self.JervisLabel.setScaledContents(True)
        self.JervisLabel.setObjectName("JervisLabel")
        self.frame = QtWidgets.QFrame(loginWindowClass)
        self.frame.setGeometry(QtCore.QRect(150, 70, 691, 591))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "border-color: rgb(255, 255, 255);\n"
                                 "border-radius: 30px;\n"
                                 "border-width: 5px 5px 5px 5px;\n"
                                 "border-style: solid;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.retryButton = QtWidgets.QPushButton(self.frame)
        self.retryButton.setGeometry(QtCore.QRect(40, 510, 181, 71))
        self.retryButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.retryButton.setStyleSheet("border-image: url(C:/Users/subha/Desktop/Final/0000 (4).png);")
        self.retryButton.setText("")
        self.retryButton.setObjectName("pushButton")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(250, 510, 181, 71))
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setStyleSheet("border-image: url(C:/Users/subha/Desktop/Final/0000 (5).png);")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.exitButton = QtWidgets.QPushButton(self.frame)
        self.exitButton.setEnabled(False)
        self.exitButton.setGeometry(QtCore.QRect(480, 510, 181, 71))
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setStyleSheet("border-image: url(C:/Users/subha/Desktop/Final/0000 (2).png);")
        self.exitButton.setText("")
        self.exitButton.setObjectName("exitButton")
        self.usernameEntry = QtWidgets.QLineEdit(self.frame)
        self.usernameEntry.setGeometry(QtCore.QRect(150, 90, 401, 101))
        self.usernameEntry.setStyleSheet("font: 30pt \"Impact\";\n"
                                         "padding-left: 10px")
        self.usernameEntry.setObjectName("usernameEntry")
        self.passwordEntry = QtWidgets.QLineEdit(self.frame)
        self.passwordEntry.setGeometry(QtCore.QRect(150, 220, 401, 101))
        self.passwordEntry.setStyleSheet("font: 30pt \"Impact\";\n"
                                         "padding-left: 10px")
        self.passwordEntry.setObjectName("passwordEntry")
        self.loginButton = QtWidgets.QPushButton(self.frame)
        self.loginButton.setGeometry(QtCore.QRect(240, 380, 181, 71))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("border-image: url(C:/Users/subha/Desktop/Final/0000 (3).png);")
        self.loginButton.setText("")
        self.loginButton.setObjectName("backButton_2")
        self.illegalEntry = QtWidgets.QLabel(self.frame)
        self.illegalEntry.setGeometry(QtCore.QRect(70, 50, 571, 441))
        self.illegalEntry.setStyleSheet("border: none;\n"
                                        "")
        self.illegalEntry.setText("")
        self.illegalEntry.setPixmap(QtGui.QPixmap("C:/Users/subha/Desktop/Final/wron_Credential.gif"))
        self.illegalEntry.setScaledContents(True)
        self.illegalEntry.setObjectName("illegalEntry")

        self.retranslateUi(loginWindowClass)
        QtCore.QMetaObject.connectSlotsByName(loginWindowClass)

    def retranslateUi(self, loginWindowClass):
        _translate = QtCore.QCoreApplication.translate
        loginWindowClass.setWindowTitle(_translate("loginWindowClass", "loginWindowClass"))
        self.usernameEntry.setPlaceholderText(_translate("loginWindowClass", "USERNAME"))
        self.passwordEntry.setPlaceholderText(_translate("loginWindowClass", "PASSWORD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginWindowClass = QtWidgets.QWidget()
    ui = Ui_loginWindowClass()
    ui.setupUi(loginWindowClass)
    loginWindowClass.show()
    sys.exit(app.exec_())
